### PR TITLE
Add design folder to develop branch

### PR DESCRIPTION
**Pull request by danidee10**
I've Started working on the speakers page.

But the main aim of this PR is to add the `design` folder to the `develop` branch.

I also had to make some changes to the [scss file](https://github.com/gbozee/pyconng/blob/7f29dd56cfb5e7b28eb7c26b0d6c187a4c94f8be/design/css/style.scss) because of the new section i added. Review and see if it's okay with you.

### CODE REVIEW

**Comment by gbozee** [comment]
did u pull from develop first because the history is a lot from the develop branch and a few things has changed

**Comment by gbozee** [comment]
a simpler solution would have been copy the design folder from master, to a temp location. Pull the latest changes from develop and then paste the folder instead of merging the changes from master to develop

**Comment by danidee10** [comment]
@gbozee i followed your suggestion. The commit log is cleaner now.

**Comment by gbozee** [comment]
Also @danidee10 it would be better if you tried submitting the pull request to the pyconng repo instead of mine

**Pull request merged**
